#!/usr/bin/env node

const path = require('path');
const expand = require('glob-expand');
const colors = require('colors');
const webfontsGenerator = require('webfonts-generator');

const files = expand({
  cwd: process.cwd(),
}, 'src/svgs/**/*.svg');

webfontsGenerator({
  files: files,
  dest: 'dist',
  fontName: 'nav-icons',
  css: true,
  cssTemplate: path.join('src/templates/_css.hbs'),
  templateOptions: {
    classPrefix: 'icon-',
    baseSelector: '.icon'
  },
  types: ['eot', 'woff2', 'woff', 'ttf', 'svg'],
  order: ['eot', 'woff2', 'woff', 'ttf', 'svg']
}, function(error) {
  if (error) {
    console.error(error);
  } else {
    console.log(colors.green(`Icon generated.`));
  }
});
